version: '3'
services:
    laravel:
        build:
            context: ./
            dockerfile: docker/production/Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        user: ${UID}:${GID}
        ports:
          - '${HTTP_PORT:-80}:80'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        restart: unless-stopped
        volumes:
            - './storage:/var/www/html/storage'
        networks:
            - main
        depends_on:
            - pgsql

    pgsql:
        image: 'postgres:alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - ./storage/volumes/postgres/data:/var/lib/postgresql/data
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - main
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

networks:
    main:
        driver: bridge
