#!/bin/bash
set -m

php /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=80 &
php /var/www/html/artisan schedule:work &
php /var/www/html/artisan queue:work --queue=high,default,low &

fg %1
wait %1
kill %2
kill %3
